"""Change auctions

Revision ID: 8d8042da7810
Revises: 126b50bb6838
Create Date: 2026-10-01 16:47:00.124549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d8042da7810'
down_revision: Union[str, Sequence[str], None] = '126b50bb6838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auctions', 'buy_now_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('auctions', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'ENDED', 'CANCELLED', name='auctionstatus'),
               nullable=False)
    op.create_index(op.f('ix_auctions_status'), 'auctions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auctions_status'), table_name='auctions')
    op.alter_column('auctions', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'ENDED', 'CANCELLED', name='auctionstatus'),
               nullable=True)
    op.alter_column('auctions', 'buy_now_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
