"""add categories

Revision ID: 93274da65cf0
Revises: aca5aa3e20ff
Create Date: 2026-10-04 17:07:01.079889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93274da65cf0'
down_revision: Union[str, Sequence[str], None] = 'aca5aa3e20ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('auctions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.alter_column('auctions', 'ended_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_auctions_category_id'), 'auctions', ['category_id'], unique=False)
    op.create_foreign_key('fk_auctions_category_id', 'auctions', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_auctions_category_id', 'auctions', type_='foreignkey')
    op.drop_index(op.f('ix_auctions_category_id'), table_name='auctions')
    op.alter_column('auctions', 'ended_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('auctions', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
